name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/rsl-org/fedora_devcontainer:latest
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    
    - name: Copy conan profile
      run: |
        mkdir -p /github/home/.conan2/profiles
        cp /root/.conan2/profiles/default /github/home/.conan2/profiles/default
    
    - name: Build project
      run: conan build . --build=missing -s build_type=Debug -o tests=True

    - name: Run tests
      run: ./build/Debug/rsl-util-test
